schema_version: 20180708
name: requesthandler
version: 0.0.16
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.96
run_image: fnproject/fn-java-fdk:jre11-1.0.96
cmd: com.example.fn.RequestHandler::handleRequest
triggers:
- name: requesthandler
  type: http
  source: /requesthandler
