schema_version: 20180708
name: elasticdataprovider
version: 0.0.15
runtime: java
build_image: fnproject/fn-java-fdk-build:jdk11-1.0.96
run_image: fnproject/fn-java-fdk:jre11-1.0.96
cmd: com.example.fn.ElasticDataProvider::handleRequest
triggers:
- name: elasticdataprovider
  type: http
  source: /elasticdataprovider
